name: Publish to Web

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Flet
        run: pip install flet --no-cache-dir

      - name: Build Web App
        run: |
          
          echo "正在打包專案: $REPO_NAME"

          flet publish main.py --distpath dist --base-url /$REPO_NAME/ --web-renderer html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
